[theme]
base="light"
primaryColor="#2196F3"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#1f1f1f"
font="sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false 